# -*- coding:utf-8 -*-
__author__ = 'alex'

ENV_GITHUB_TOKEN = "GITHUB_TOKEN"
ENV_OPENAI_KEY = "OPENAI_API_KEY"
ENV_OPENAI_PROXY = "OPENAI_PROXY"
ENV_GEMINI_KEY = "GEMINI_API_KEY"
ENV_SECRET_KEY = "SECRET_KEY"
ENV_SERVER_PORT = "SERVER_PORT"
ENV_DEBUG = "DEBUG"

