# -*- coding:utf-8 -*-
#  Copyright (c) 2016-present The ZLMediaKit project authors. All Rights Reserved.
#  This file is part of ZLMediaKit(https://github.com/ZLMediaKit/Github-AI-Assistant).
#  Use of this source code is governed by MIT-like license that can be found in the
#  LICENSE file in the root of the source tree. All contributing project authors
#  may be found in the AUTHORS file in the root of the source tree.
#
__author__ = 'alex'

# Environment variables

# Model used for translation
ENV_TRANSLATION_MODEL = "TRANSLATION_MODEL"
ENV_TRANSLATION_API_REQUEST_LIMIT = "TRANSLATION_API_REQUEST_LIMIT"
ENV_TRANSLATION_API_KEY = "TRANSLATION_API_KEY"
ENV_TRANSLATION_API_URL = "TRANSLATION_API_URL"
ENV_TRANSLATION_API_MAX_INPUT_TOKENS = "TRANSLATION_API_MAX_INPUT_TOKENS"
ENV_TRANSLATION_API_MAX_OUTPUT_TOKENS = "TRANSLATION_API_MAX_OUTPUT_TOKENS"

# Model used for review
ENV_REVIEW_MODEL = "REVIEW_MODEL"
ENV_REVIEW_API_REQUEST_LIMIT = "REVIEW_API_REQUEST_LIMIT"
ENV_REVIEW_API_KEY = "REVIEW_API_KEY"
ENV_REVIEW_API_URL = "REVIEW_API_URL"
ENV_REVIEW_API_MAX_INPUT_TOKENS = "REVIEW_API_MAX_INPUT_TOKENS"
ENV_REVIEW_API_MAX_OUTPUT_TOKENS = "REVIEW_API_MAX_OUTPUT_TOKENS"

ENV_TRANSLATION_TARGET_LANG = "TRANSLATION_TARGET_LANG"
ENV_TRANSLATOR = "TRANSLATOR"
ENV_GITHUB_TOKEN = "GITHUB_TOKEN"
ENV_GITHUB_USERNAME = "GITHUB_USERNAME"
ENV_SECRET_KEY = "SECRET_KEY"
ENV_DEBUG = "DEBUG"
ENV_AUTO_RELOAD = "AUTO_RELOAD"
ENV_PROXY_URL = "PROXY_URL"
ENV_WEB_HOOK_LISTEN_HOST = "WEB_HOOK_LISTEN_HOST"
ENV_WEB_HOOK_LISTEN_PORT = "WEB_HOOK_LISTEN_PORT"
ENV_WEB_HOOK_WORKERS = "WEB_HOOK_WORKERS"
ENV_WEB_HOOK_ACCESS_LOG = "WEB_HOOK_ACCESS_LOG"
